
# Map basic input data

```{r}
source("./0_Libraries.R")
# get county boundary and water
la_county <- get_county_boundary() %>%
  st_transform(proj_crs)

la_city <- get_city_boundary(proj_crs) %>%
  st_transform(proj_crs)

# get water
la_water <- area_water(state="CA", county="Los Angeles")%>%
  st_transform(proj_crs) %>%
  clipintersect_boundary(la_city)
  
la_food <- foodpoi_plot %>%
  filter(!is.na(LONGITUDE)) %>%
  st_as_sf(coords=c("LONGITUDE", "LATITUDE"), crs=4326) %>%
  st_transform(proj_crs) %>%
  clipintersect_boundary(la_county)


osm_parks <- getbb("Los Angeles County", display_name_contains = "United States") %>%
  opq() %>% 
  add_osm_feature(key = "leisure", value=c("park", "nature_reserve", "golf_course")) %>% 
  osmdata_sf()

la_parks <- osm_parks$osm_polygons %>%
  st_transform(proj_crs) %>%
  clipintersect_boundary(la_city)
  

# get major highways

```

## Mapping study area

```{r}

tm_shape(la_city) +
  tm_polygons(col = "lightgrey", fill_alpha=.2) +
  tm_shape(la_county) +
  tm_borders() + 
  tm_shape(la_water) +
  tm_fill(col="lightblue", lwd=0) +  
  tm_shape(la_parks) +
  tm_polygons(col="lightgreen") + 
  tm_layout(inner.margins = c(0.1, .1, 0.2, 0.1)) +
  tm_scale_bar()

```

## Mapping food access poi

```{r}

tm_shape(la_city) +
  tm_borders() +
  tm_shape(la_food) +
  tm_dots("zhang-2025", size = 0.01)

```

## Mapping population weighted census tract centroids

```{r, include=FALSE}
tmap_mode("plot")


tm_shape(la_ct) +
  tm_borders(col="grey") +
  tm_shape(la_ctcent_dat) +
  tm_dots(col = "red", size = 0.02) +
    tm_shape(la_ct_wtcent_dat) +
  tm_dots(col = "purple", size = 0.02) +
  tm_layout(legend.position = c("left", "bottom")) + 
  tm_scale_bar()

tm_shape(la_county) +
  tm_borders() +
  tm_shape(la_hh_sample) +
  tm_dots(col = "black", size = 0.01) +
  tm_layout(legend.position = c("left", "bottom"))

```

# Inspecting point datasets

```{r}
# Select a random census tract
set.seed(123)
random_tract <- la_ct %>% slice_sample(n = 1)

# Find adjacent tracts
adjacent_tracts <- la_ct[st_touches(random_tract, la_ct, sparse = FALSE), ]

# Plot the selected and adjacent tracts
tmap_mode("view")

tm_shape(random_tract) + 
  tm_borders(lwd = 2, col = "red") + tm_fill(col = "pink", alpha = 0.5) +
  tm_shape(adjacent_tracts) + 
  tm_borders(lwd = 2, col = "blue") + tm_fill(col = "lightblue", alpha = 0.5) +
  tm_shape(la_ctcent_dat) +
  tm_dots(col = "red", size = 0.01) +
  tm_shape(la_ct_wtcent_dat) +
  tm_dots(col = "green", size = 0.01) +
  tm_shape(la_ct) + 
  tm_borders() +
  tm_layout(legend.position = c("left", "bottom"))

## TODO look into tracts with strange behavior ID = 980016, 990200 + 599100 (in the middle of ocean)

```

# Mapping POI and population-weighted centroids data

```{r}
tm_shape(la_county) +
  tm_borders() +
  tm_shape(food_23_24_SSI) +
  tm_dots(col = "red", size = 0.01) +
  tm_shape(la_ct) +
  tm_borders() +
  tm_shape(la_ctcent_dat) +
  tm_dots(col = "purple", size = 0.01) +
  tm_layout(legend.position = c("left", "bottom"))

```

## Map terrain elevation and street network features

```{r}

elev <- get_dem("socal", proj_crs)

tmap_options(check.and.fix = TRUE)

tm_shape(elev) +
  tm_raster(palette = terrain.colors(100), style = "cont", title = "Elevation (m)")+ 
  tm_shape(la_county) + 
   tm_borders(col = "black", alpha=.5)


```

## Visualizing OSM

```{r}
  osm_lines <- get_osm(bbox=lac_bbox)
  ht = c("raceway") # highway types to remove
  # highway types https://wiki.openstreetmap.org/wiki/Key:highway#Roads
  osm_paths = osm_lines[!(osm_lines$highway %in% ht), ]
  plot(osm_paths["highway"], key.pos = 1)
  
  rm(osm_lines, osm_paths)
  
  #not enough heap space to run this 
  #network <- street_network_to_sf(r5r_core)


```
